services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: winson
      POSTGRES_PASSWORD: password
#      where to store data
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
volumes:
  db: